### ISSUE TITLE
Test breadboard.bat for compatibility with JDK 7, 8, and 9

### ISSUE THREAD

**Issue by disperse** [human-nature-lab/breadboard#129]
It looks like `activator dist` creates a breadboard.bat in the `bin` directory. Compare that to the `breadboard.bat` we used to include with v2.2.4 and look at the changes made to the `breadboard` file referenced here: https://github.com/human-nature-lab/breadboard2/issues/29

**Comment by wyattis** [comment]
Works fine with all 3, but java 9 requires `set _JAVA_OPTIONS="--add-modules=java.xml.bind"` to be set before running. I have been running java 9 using:

    setlocal
        set _JAVA_OPTIONS="--add-modules=java.xml.bind"
        "C:\Program Files\Java\jdk-9.0.4\bin\java" -cp "./lib/*;" -Dhttps.port=9443 -Dapplication.secret="pleasechangethis" -Dconfig.file=conf\application-prod.conf play.core.server.NettyServer .
    endlocal

I've added an issue to add this information about java 9 to the documentation.
