### ISSUE TITLE
Import/Export experiments via the browser

### ISSUE THREAD

**Issue by wyattis** [human-nature-lab/breadboard#13]

**Comment by disperse** [comment]
This replaces the requirement to copy experiment folders to the 'experiments' directory directly.

**Comment by disperse** [comment]
Possibly add this for v2.3

**Comment by wyattis** [comment]
Browser side of this is functional. Import sends a zip file and an experiment name to `ExperimentController.importExperiment`. Export returns a zipped stream from `ExperimentController.exportExperiment` which is downloaded in the background on the client side.
