### ISSUE TITLE
Make client view responsive for mobile devices

### ISSUE THREAD

**Issue by disperse** [human-nature-lab/breadboard#27]
This will require resizing the d3js visualization and text and allowing for both vertical (visualization over text) and horizontal orientations.

**Comment by wyattis** [comment]
Basic resizing and layout change happens for mobile devices. Could potentially have resizable graph. Still needs more testing.

**Comment by disperse** [comment]
Can we mark this as done for v2.3 and re-label it with a v2.3.1 tag?

**Comment by disperse** [comment]
This is done in v2.3
