### ISSUE TITLE
Fix TimersCtrl when providing multiple timers

### ISSUE THREAD

**Issue by disperse** [human-nature-lab/breadboard#34]
Let's merge the TimersCtrl2 code with v2.3.

**Comment by wyattis** [comment]
Merged TimersCtrl2. Need to handle timers using "time remaining" instead of using timestamps on the client side.

**Comment by wyattis** [comment]
Sounds like there is an issue with timers not showing up on the client side unless another change has been made to the graph too. Quick fix could be to change a single property (maybe called "timer_updated") on the vertex that the timer is being added to.

**Comment by disperse** [comment]
Fixed with commit 8e8d3fbb2771d091c3128b65a6e5c7d7a7576ec5
