### ISSUE TITLE
Pretty-print node objects in Player dialog

### ISSUE THREAD

**Issue by disperse** [human-nature-lab/breadboard#41]
Currently Hashmap and Array properties of the player are not displayed.

**Comment by disperse** [comment]
This might be easy, if so, let's do it for v2.3. Otherwise, it is not a priority.

**Comment by wyattis** [comment]
Shows all nested data as pretty JSON now, but should probably be converted to a dropdown style like chrome dev-tools.

**Comment by disperse** [comment]
Let's look at this when doing the three-column layout for the players dialog

**Comment by disperse** [comment]
Merged into #168
