### ISSUE TITLE
More consistent image import/export

### ISSUE THREAD

**Issue by wyattis** [human-nature-lab/breadboard#92]
Right now the images are referenced by ID in the breadboard code, but export saves them by name without the ID and import autoincrements the ID. This leads to inconsistencies each time an experiment is exported/imported.

**Comment by wyattis** [comment]
One solution might be to reference all of the images by name instead of ID. This could work better if the users are able to rename images to make them more meaningful as well.

**Comment by disperse** [comment]
This ticket replaces #2

**Comment by disperse** [comment]
Implemented in the file-dev branch around commit 7d99a9c93f52ecdd70e3df8e9334d03627c1e713
