### ISSUE TITLE
Limit repeat play using AMT Qualifications

### ISSUE THREAD

**Issue by wyattis** [human-nature-lab/breadboard#97]
- Add UID field to experiment table
    - Optionally keep this UID when copying experiment
- Create dialog to assign qualifications to a list of worker IDs
- Limit repeat play by checking if worker qualifications instead
- Assign qualification upon completion of experiment (`breadboard.completed={UID}`)
- Import/Export UID of experiment in meta file
    - Optionally keep this UID on import or generate a new one
- Add experiment name and UID to RequestorAnnotation field when creating a HIT
- Parse the UID and name from the RequestorAnnotation in the AMT dialog
- CompletedAt should be determined based on the existence of the Qualification for that experiment (`breadboard.completed={UID}`)

**Comment by disperse** [comment]
Implemented with commit 1c4589cb89c28be0f4fff058d08602062b20a6c5
